{% set name = "dependencies" %}
{% set version = "7.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 781864f3349d0b22b7dd8cbabb101f4eaea99e3f8dc32c314e78d4147cc0fe76

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10

test:
  imports:
    - dependencies

about:
  home: https://github.com/dry-python/dependencies
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Dependency Injection for Humans
  description: With help of DI you can use different parts of you system independently and combine their behavior really easy.
  doc_url: http://dependencies.readthedocs.io/en/latest/
  dev_url: https://github.com/dry-python/dependencies

extra:
  recipe-maintainers:
    - nicoddemus
