travis:
  secure:
    BINSTAR_TOKEN: pZd8BDeYUDAJ3neTum6LPUNa9n22BTuMS8KKD1HpKjT3cUZRKALy9CmaC/z5LVzOGIz1OWrIEUlZl44ok1Lez+8JyTTaigP/wAq+Do1vZXSIrEgMBgPHenYP/+Fys+lVc04kLOGFX1IcQd1MboKdKzk59EzQ2CwTVfJuDPxz9YvOIAcSbeLnP9r9nvJII1lNRD9iOR3spPCE7a1Er1TlUf9VWL1rihMmx57DDlcihH4wVwb+91Tin1gorly7y9RYGTxoTYTAlLzTUk94vmKz7MO236PcSIyz+gVV5+JCeuPcWiZAEjBPu1geBu+xx2piSoHtbveANXVIRqjcDzHN3SyFqS1ODiT012TDVQsTaVrSxUKd1wG/S07UzI4ngNTDl5RqBQrCY707m8ws80OQdo2Lqzl9CVp5nvrgdoMsfSps/KQhZiW31X0d8uZebYYwd8QW64semIa4IQDlY8kgbSxLHJ4gc9DfjLUHAB+Oqzuvn0SUsHHLZgG+9KaWyooL9KMAFP88BTi3skzsFu60KrAK/sibNeRsJwDX+uQTs9ADkw59ibSH8CpBVPwIBY/7G29rQ/BM27NepszvZ49p7paut0IkYrfzwNPRYpeq9PaEc3ieyo+02DkF2ePx8BIMm71drSVux2X0aOv/efgP1bEN+nAM09tJP05CdDU9BB4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
