travis:
  secure:
    BINSTAR_TOKEN: I3yG+4/Dj9nLbW9pG547PM9+1tTQ+oN2HF8Dqvj+yA2wcMqdOjIKWDTxuVeNTkEBEzIu5ZR++ROOGHziqO7JX2npoWBIpzVsqTMn5vfCIdmFUugTn4kw0hkdPQLeXy8zDUSIgWotlQZvtJyR7Dn3JoPphT2g9rky1ZIxAXK8qKd6lFJ4CR8ceojqMc/dxnquqJtvPEYiCjvGF+qBvT/yhdMutiYKMOze/KQRDCiPfU7qSWhLRwbiLQ5+q7+tNZbChK8ejvYla97WVBD0wkr1iHoRSsaiOTnSnQviWLfBcExxU1aWZtydl8vs875yjryWcqTB6now8+KICpfBFqv97A9KizQqAevswmHX/XWHdEApd1jpDDG2qNYkgRr52kNCs46vqTjaHgn0lKLWEts9wCATFjaoWzMjW/yvnDz20zTq+WGz6Y+DBnbFn/eEf+2TA5cI7NHdmh5en8kLn4OvADPP07/jaRG9tu4T08DMA6Eb6n4td+18OfHMzrTq9ZiwEBzG8fGdpEvJceEiZOPgUYYTMgREGIduykt1rQSrL0Bx6tZmicxsFdUoDTx0GGOZlpNnjOPaUmfcZ3Zk2TwicsGmTWbqtBSV+t4FuNRrnCUvw9sM8DbveT0V6CrZAW2M1F3IwkFXD147Z2Ft3cb+K+iUNYfeeqvXcdnl87NuZ3E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
